version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3306"          # host:3307 → container:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql

  todo-app:
    build: .
    container_name: todo-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"          # host:8080 → container:8080

volumes:
  mysql_data:
